In [1]:
import pandas as pd
import numpy as np
from joblib import Parallel, delayed

df = pd.read_csv("C:/Users/usuario/Desktop/archivos_base_python_data_science_big_data_esencial/basedatos2008.csv", nrows=100000)

In [2]:
df_sub = df[["CarrierDelay","WeatherDelay","NASDelay","SecurityDelay","LateAircraftDelay"]]
df_sub.head(30)

    CarrierDelay  WeatherDelay  NASDelay  SecurityDelay  LateAircraftDelay
0            NaN           NaN       NaN            NaN                NaN
1            NaN           NaN       NaN            NaN                NaN
2            NaN           NaN       NaN            NaN                NaN
3            NaN           NaN       NaN            NaN                NaN
4            2.0           0.0       0.0            0.0               32.0
5            NaN           NaN       NaN            NaN                NaN
6           10.0           0.0       0.0            0.0               47.0
7            NaN           NaN       NaN            NaN                NaN
8            NaN           NaN       NaN            NaN                NaN
9            NaN           NaN       NaN            NaN                NaN
10           NaN           NaN       NaN            NaN                NaN
11           8.0           0.0       0.0            0.0               72.0
12           NaN           NaN       NaN            NaN                NaN
13           NaN           NaN       NaN            NaN                NaN
14           NaN           NaN       NaN            NaN                NaN
15           NaN           NaN       NaN            NaN                NaN
16           3.0           0.0       0.0            0.0               12.0
17           NaN           NaN       NaN            NaN                NaN
18           0.0           0.0       0.0            0.0               16.0
19          12.0           0.0       0.0            0.0               25.0
20           NaN           NaN       NaN            NaN                NaN
21           7.0           0.0       0.0            0.0               12.0
22           NaN           NaN       NaN            NaN                NaN
23           NaN           NaN       NaN            NaN                NaN
24           NaN           NaN       NaN            NaN                NaN
25           NaN           NaN       NaN            NaN                NaN
26          40.0           0.0       0.0            0.0                7.0
27           NaN           NaN       NaN            NaN                NaN
28           NaN           NaN       NaN            NaN                NaN
29           NaN           NaN       NaN            NaN                NaN

In [3]:
def retraso_maximo(fila):
    if not np.isnan(fila).any():
        names = ["CarrierDelay","WeatherDelay","NASDelay","SecurityDelay","LateAircraftDelay"]
        return names[fila.index(max(fila))]
    else:
        return "None"

In [ ]:
result = []
for fila in df_sub.values.tolist():
    result.append(retraso_maximo(fila))

In [ ]:
result

In [ ]:
result = Parallel(n_jobs =2, backend="multiprocessing")(
    map(delayed(retraso_maximo), df_sub.values.tolist()))

In [ ]:
result